### PR TITLE
chore(deps): upgrade to @mapbox/node-pre-gyp

### PR DESCRIPTION
**Pull request by cschanaj**
This PR upgrade the deprecated package `node-pre-gyp` to `@mapbox/node-pre-gyp`. 

`@mapbox/node-pre-gyp` requires Node 8+ and AWS SDK will only support Node 10+ starting from November 2021. So I have bump the Node version in the CI to Node 10+ as well. 

```
The AWS SDK for JavaScript (v2) will no longer support Node.js v8.17.0
as of November 1, 2021. To continue receiving updates to AWS services
and bug fixes please upgrade to Node.js 10.x or later
```

P.S. Please squash and merge if it is preferred. thanks.

### CODE REVIEW

**Comment by cschanaj** [comment]
This PR closes #69 and bumped the supported Node versions. @codeplea would you mind to take a look at this PR and kindly consider reviewing & merging? thanks.

**Comment by codeplea** [comment]
Thanks. I will look into it when I have time. Could be a couple weeks.

**Comment by cschanaj** [comment]
thanks. please feel free to ping me anytime if any modification is needed. 😄

**Comment by rafiqlightwala** [comment]
please process this

**Comment by codeplea** [comment]
Thanks! It seems to be working and binaries are building and being published for Windows at the moment.

FYI, the travis-ci is now broken. I haven't dealt with them lately, and I'm not entirely sure what it'll take to fix it.

**Comment by codeplea** [comment]
Turned out to be way more work than I was hoping for, but travis-ci is now mostly working too.

**Comment by cschanaj** [comment]
It seems that a newer GCC version is required to build tulipnode with the Node 16 headers, see #72

**Pull request merged**
