### PR TITLE
chore: add built-in typescript declarations

### PR DESCRIPTION
**Pull request by cschanaj**

### CODE REVIEW

**Comment by cschanaj** [comment]
@codeplea this PR add a built-in typescript declarations for the npm package, would you be interested to review this?

**Comment by codeplea** [comment]
It looks good to me, but I haven't used typescript myself, so my concern is for future maintenance.

**Comment by fibo** [comment]
@codeplea can we merge this? I can help with maintenance but I think it will not be hard to maintain unless the original Tulip library changes often.

**Comment by codeplea** [comment]
No, I don't want to have to go through this on each ti update. If you want to write a script that generates the file automatically (e.g. fills in IndicatorType and IndicatorIndentifier) then I could probably merge that.

**Comment by fibo** [comment]
It also could be a gods idea.

I already did something similar, generating TypeScript definitions with a script.

Also tulind already lists its indicators.

I am sleepping here (at Imperia in the Riviera)

image

**Pull request closed without merging**
